# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-20 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteSejaUfsm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato_administrativo',
            name='Setor',
            field=models.CharField(blank=True, max_length=100, verbose_name='Endereço'),
        ),
    ]
