# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-15 04:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SiteSejaUfsm', '0002_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='Tipo',
        ),
        migrations.AlterField(
            model_name='imagen',
            name='Noticia',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='SiteSejaUfsm.Noticia'),
        ),
    ]
