# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-15 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SiteSejaUfsm', '0003_auto_20171215_0203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagen',
            old_name='Original',
            new_name='Imagem',
        ),
        migrations.RemoveField(
            model_name='imagen',
            name='Noticia',
        ),
        migrations.AddField(
            model_name='curso',
            name='Imagem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SiteSejaUfsm.Imagen'),
        ),
        migrations.AddField(
            model_name='curso',
            name='Noticia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SiteSejaUfsm.Noticia'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='Imagem',
            field=models.ImageField(blank=True, null=True, upload_to='galeria'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='Imagem_2',
            field=models.ImageField(blank=True, null=True, upload_to='galeria'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='Imagem_3',
            field=models.ImageField(blank=True, null=True, upload_to='galeria'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='Imagem_4',
            field=models.ImageField(blank=True, null=True, upload_to='galeria'),
        ),
    ]
