# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-15 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteSejaUfsm', '0004_auto_20171215_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='Logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos'),
        ),
    ]
