# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-15 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SiteSejaUfsm', '0007_auto_20171215_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagen',
            name='idnoticia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SiteSejaUfsm.Noticia', verbose_name='Notícia'),
        ),
        migrations.AlterField(
            model_name='video',
            name='URL',
            field=models.URLField(blank=True, max_length=300),
        ),
    ]
