# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-15 15:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SiteSejaUfsm', '0008_auto_20171215_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='Imagem',
        ),
    ]
